# Generated by Django 4.2.16 on 2024-11-21 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='category',
            field=models.CharField(choices=[('뉴스', '뉴스'), ('기획', '기획'), ('리뷰', '리뷰'), ('인터뷰', '인터뷰'), ('칼럼', '칼럼'), ('평론', '평론'), ('영화제', '영화제')], max_length=50),
        ),
    ]
