# Generated by Django 4.2.16 on 2024-11-21 16:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boards', '0003_newsarticle_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsarticle',
            name='url',
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='liked_users',
            field=models.ManyToManyField(blank=True, related_name='liked_articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='likes_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
