# Generated by Django 4.2.16 on 2024-11-22 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_remove_newsarticle_url_newsarticle_liked_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='url',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='date',
            field=models.DateField(default='', null=True),
        ),
    ]
